version: 0.2

phases:
  build:
    commands:
      - echo "Zipping deployment package..."
      - zip -r deployment_package.zip . -x buildspec.yml "*.env"
artifacts:
  files:
    - '**/*'
  discard-paths: no
  base-directory: ./